### ISSUE TITLE
Running initial_setup.py

### ISSUE THREAD

**Issue by kevjumba** [jasbur/RaspiWiFi#6]
find: ‘/run/user/1000/gvfs’: Permission denied
Traceback (most recent call last):
  File "initial_setup.py", line 47, in <module>
    update_config_paths()
  File "initial_setup.py", line 9, in update_config_paths
    project_path = subprocess.check_output(['find', '/', '-name', 'GSbSFZwWV1mig4vFSmbLW9iP8TfGfMYCPfHTqGcD'])[:-42].decode('utf-8')
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['find', '/', '-name', 'GSbSFZwWV1mig4vFSmbLW9iP8TfGfMYCPfHTqGcD']' returned non-zero exit status 1

**Comment by jasbur** [comment]
Changed the way that the "find" command is called from the intiial_setup.py script. Initial setup should be working now.
